### ISSUE TITLE
Suggestion: Don't put alphabet (S, A, B, C, D) on usage rate

### ISSUE THREAD

**Issue by lohszeying** [appsample-com/spiral-abyss#15]
Usage rate is not an indicator of character strength. As your website gets more popular (EN playerbase / CN playerbase uses your website now), it could cause more misunderstanding of character strength due to usage rate, especially with alphabet (S, A, B, C, D) which looks very similar to a tier list.

Xiangling, for example, is a very strong unit and is meta in the game, but is listed under "C" tier in your usage rate. It could cause some misunderstanding and people would think Xiangling is very weak, only at "C" tier.

What I would suggest is to just remove "S", "A", "B", C" and "D" so it does not look like a tier list.

**Comment by appsample-com** [comment]
Hi! In a recent update the alphabet has been replaced with a star. But as long as there are numbers people will still compare one with another, there aren't really a way to make it not like a tier list. It's an open question though

**Comment by lohszeying** [comment]
Hello! I've just seen your updated website and I think it looks better now. I understand that people will still compare one with another but hopefully this will lessen the "omg look at Hu Tao A tier while Diluc is in D tier" when both of them are good in different situation (Diluc has no caveat, easy to play, slightly better AoE than Hu Tao and good in sustained, Hu Tao have high damage in exchange for a lot of caveats and good in bursty style of gameplay). Thanks a lot for updating your website!
