### ISSUE TITLE
Suggestion: Deprecated % should change to character >=80

### ISSUE THREAD

**Issue by CB2Stanley** [appsample-com/spiral-abyss#16]
I think most people who have enough resources will level up their character to 70+ in order to get a free pull.
The indication of deprecated rate shouldn't be >= 70, it just simply can't indicate anything.
I think 80 / 80+ is a more appropriate number for it, since it require more resources and less incentive and can give a much clearer view.
Thanks a lot for your hard work.

**Comment by appsample-com** [comment]
@CB2Stanley Hi! But we think that Lv 70 is qualified for battles, especially for those supporting characters. Raising it to 80 will lead to a lost of data.

**Comment by appsample-com** [comment]
Now it's set to 71... let's see how it goes
