### ISSUE TITLE
Feature Request: Without Filter

### ISSUE THREAD

**Issue by briana-jin-zhang** [appsample-com/spiral-abyss#2]
I really love the feature that allows you to generate your own team comps when searching. What I would like is if we could add a "without" filter since for example, venti and zhongli are recommended for all teams but players might not have them. Thank you for all the work done so far!

**Comment by appsample-com** [comment]
Hi @briana-jin-zhang , you could use this newly added toggle to filter out teams. Click any character that you don't want to make it gray, then hit the "Filter Char" toggle at the bottom.

Thanks and enjoy!

![2021-06-28 160435](https://user-images.githubusercontent.com/86268796/123710230-99c5c300-d82b-11eb-9b62-56112824383f.png)
