### ISSUE TITLE
Feature Request: Select Data Source

### ISSUE THREAD

**Issue by theonaku** [appsample-com/spiral-abyss#3]
Due to the recent release of Kazuha, there's a lot of discussions about his usage and performance in the abyss. But currently all data source are mixed up, so it is not that easy to analyse his data. I think it will be pretty convenient if the phase of abyss can be selected, like only viewing the data from phase 07/01 ~ 07/16.

**Comment by appsample-com** [comment]
Hi @theonaku - yes the team did think about it. We are still handling some performance issues but I believe this future will launch by Genshin patch 2.0

**Comment by appsample-com** [comment]
by the way we just deleted all 6/16-7/01 data to temporary solve this problem

**Comment by theonaku** [comment]
That looks more intuitive now! Thanks.
