### ISSUE TITLE
Does it include Asia server data

### ISSUE THREAD

**Issue by crack355** [appsample-com/spiral-abyss#5]
I was interested in seeing if anybody had used the same team as I to get 9* clears, but noticed that my team doesn't appear in any of the 9* Make Your Combo options. Just curious if data submitted from English Asia server profiles isn't included yet or if a team won't appear in Make Your Combo if not enough people have used it.

**Comment by appsample-com** [comment]
Hi! It could be one of following reasons:
* mihoyo's serve was having an issue when we made the request
* your battle info is not public
* the battle record is out of date, for example on 1st/16th of every month we'll clean up a lot of records.

But you don't need to submit your uid again. it will be queued and fetched 5~7 days later
