### ISSUE TITLE
Feature Request: Tier list with filtered data source

### ISSUE THREAD

**Issue by jimmyyou** [appsample-com/spiral-abyss#8]
Request: After the user filters out characters that he/she does not have, can we show an updated tier list that is generated from the filtered data source? This can be added as another tier list that is separated from the main tier list.

Reasoning: Zhongli is currently the number 1 on the tier list, but if I exclude Hutao and Xiao (which I unfortunately do not have), most of the popular team comps do not have Zhongli. This suggests that for a user without Hutao or Xiao, Zhongli's utility is much lower than what is shown in the main tier list.

Most users does not have all characters. This feature would be useful to measure the utility of adding a new character to a limited character pool.

**Comment by appsample-com** [comment]
@jimmyyou That's a great idea but we have some technical issues here - each time we generate the stats we'll need to transfer >300MB of data from database to our application. So currently we can not do any personalized reports for users until we find a way out
