### ISSUE TITLE
Feature Request: Save available character as a JSON upload/download & filter 1.6 vs 2.0 - -or is there a 2.0 update?

### ISSUE THREAD

**Issue by Madman-08** [appsample-com/spiral-abyss#9]
Seems like a really cool tool, but ya being able to look at each spiral abyss release on it's own would be a nice touch, as the floor changes and buffs change teams used substantially I'd think. that said; It still says "1.6" so I am just assuming plans for 2.0 exist.

If update plans do exist, then having the ability to save the selected/unselected characters would be nice, they do that json load here - https://seelie.inmagi.com/settings if you want to see what I mean. It works pretty slick.

**Comment by appsample-com** [comment]
Hi @Madman-08 ! We put the archives here https://github.com/appsample-com/spiral-abyss/tree/main/archives
Since our json schema is changing all the time, so we can't ensure the old datasets can be parsed in current application.
