### ISSUE TITLE
How about collect data when user do their daily check-in?

### ISSUE THREAD

**Issue by ForestHouse2316** [appsample-com/spiral-abyss#92]
Hi, I'm a dev of GADC [A tiny program...](https://github.com/ForestHouse2316/Genshin_Auto_Daily_Check-in)
Honestly, I haven't used this site,
but recently I heard your site cannot collect abyss data anymore because of HoYoLAB patch.
Only acc owners can check them, right?
From the dev's point of view, if users are reluctant to offer their information,
how about collecting that by offering an auto check-in service? (Also with explicit terms&policy abt personal info collecting)
If then, more users will willingly agree and offer their information than a program that does not have any other functions.
__That is, making an all-in-one tool!__
(MiHoYo only prohibits game plugins that directly access the client program. So unless they consider this kind of program as a "plug-in", it would be possible to sustain this site.)

**Comment by ForestHouse2316** [comment]
My program's accessibility is quite bad I think
but if you made that program as a shape of Chrome extending program, it would be much easier to use.

**Comment by soap231** [comment]
I will use it if it is a Chrome extension from Chrome Store

**Comment by ForestHouse2316** [comment]
> I will use it if it is a Chrome extension from Chrome Store

But this task needs direct access abt URL control,
that Chrome extension program might be just kinda "reminder" program if it cannot execute commands like that.
That's why I've made my program's main task not dependent on Chrome.
(so that I can control various things. Cuz there is no Chrome's interference out of it.)

But I'll try making something kind of Chrome extension, even if it is just a reminder program...

**Comment by Metigh** [comment]
I'll be glad if u guys make it work somehow, this website was always a big help for making team comps for me.

**Comment by baoanhng** [comment]
This site is obsolete and probably need a new one. In the survey they don't even bother sort the characters for alphabet.

**Comment by ForestHouse2316** [comment]
> This site is obsolete and probably need a new one. In the survey they don't even bother sort the characters for alphabet.

Can I ask you a question..?
I'm making a desktop application using the Electron. Would it be able to replace this site?
(because it is being made by the Electron, making web is also available at once)
